package com.__CORP_NAME__.it.__APP_NAME__.model.framework;

public enum ApplicationMessageId {
  GENERIC_INTERNAL_ERROR_MESSAGE,
  GENERIC_BAD_CLIENT_DATA_ERROR_MESSAGE,
  GENERIC_MISSING_REQUEST_PARAMETERS_ERROR_MESSAGE,
  GENERIC_INCONSISTENT_CLIENT_DATA_ERROR_MESSAGE,
  API_REQUEST_VALIDATION_ERROR_MESSAGE,
  API_REQUEST_PARAMETERS_VALIDATION_ERROR_MESSAGE,
  UNCAUGHT_EXCEPTION_INTERCEPTED_MESSAGE,
  VALIDATION_ERROR_MESSAGE_TEMPLATE,
  ID_OR_NAME_FILTER_ERROR
}
